### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by n1lby73** [jerry08/Y2mateApi#1]
can you please provide more details on how to use this with other framework like python

**Comment by jerry08** [comment]
I'm not a python developer so I won't be able to provide much assistance with that. It's possible to build an exe file for you to use via command line though.

**Comment by n1lby73** [comment]
just to get you right, your talking of windows, when you mentioned exe right?

**Comment by jerry08** [comment]
Yes. That's correct.

**Comment by n1lby73** [comment]
got no idea about that, unless you'll provide it for others who might contribute when they see it

**Comment by jerry08** [comment]
I will close this since it's related to a different programming language entirely.
